#!/bin/bash

sqlite3 -batch -line database.sqlite3 'SELECT * FROM players'
sqlite3 -batch -line database.sqlite3 'SELECT * FROM techniques'
sqlite3 -batch -line database.sqlite3 'SELECT * FROM tools'
